# -*- coding: utf-8 -*-
"""SEPIEnrollment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wcfQiDTvX6LtuKxQkBn1l4UbkBupEY6a
"""


# streamlit_enrollment_form.py
import streamlit as st
from fpdf import FPDF
from uuid import uuid4
from datetime import datetime
import os
import unicodedata

# Light pink background with logo watermark
st.markdown(
    """
    <style>
    body, .stApp {
        background-color: #fff0f5;
        background-image: url('SEPI%20LOGO.png');
        background-size: 200px;
        background-repeat: no-repeat;
        background-position: top right;
        opacity: 0.95;
    }
    </style>
    """,
    unsafe_allow_html=True
)

def safe_text(text):
    return unicodedata.normalize("NFKD", text).encode("latin-1", "ignore").decode("latin-1")

st.set_page_config(page_title="School of Everlasting Pearl, Inc Enrollment System")
st.title("📄 School of Everlasting Pearl, Inc Enrollment System")

st.subheader("A. Personal Data")
full_name = st.text_input("Full Name")
age = st.text_input("Age")
birth_date = st.text_input("Birth Date")
birth_place = st.text_input("Birth Place")
lrn = st.text_input("LRN (optional)")
grade_level = st.text_input("Enrolling for Grade Level")
address = st.text_input("Home Address")
contact = st.text_input("Contact Details")
previous_school = st.text_input("Previous School (optional)")

st.subheader("B. Family Data")
mother_name = st.text_input("Mother's Full Name")
mother_age = st.text_input("Mother's Age")
mother_nationality = st.text_input("Mother's Nationality")
mother_religion = st.text_input("Mother's Religion")
mother_contact = st.text_input("Mother's Contact Number")
mother_education = st.selectbox("Mother's Highest Educational Attainment", ["Elementary", "High School", "College Graduate", "Master's", "Doctorate", "Other"])
mother_employment = st.text_input("Mother's Employment")

dad_name = st.text_input("Father's Full Name")
dad_age = st.text_input("Father's Age")
dad_nationality = st.text_input("Father's Nationality")
dad_religion = st.text_input("Father's Religion")
dad_contact = st.text_input("Father's Contact Number")
dad_education = st.selectbox("Father's Highest Educational Attainment", ["Elementary", "High School", "College Graduate", "Master's", "Doctorate", "Other"])
dad_employment = st.text_input("Father's Employment")

marital_status = st.selectbox("Parents' Marital Status", ["Married", "Separated", "Widowed", "Single Parent", "Other"])

st.subheader("C. Guardian Information")
guardian_name = st.text_input("Guardian Full Name")
guardian_relation = st.text_input("Relationship to the Student")
guardian_address = st.text_input("Guardian Address")
guardian_contact = st.text_input("Guardian Contact Number")
