# -*- coding: utf-8 -*-
"""SEPIEnrollment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wcfQiDTvX6LtuKxQkBn1l4UbkBupEY6a
"""

# streamlit_enrollment_form.py
import streamlit as st
from fpdf import FPDF
from uuid import uuid4
import os
import unicodedata

def safe_text(text):
    return unicodedata.normalize("NFKD", text).encode("latin-1", "ignore").decode("latin-1")

st.set_page_config(page_title="Enrollment Form Generator")
st.title("📄 Enrollment Form Generator")

st.subheader("A. Personal Data")
full_name = st.text_input("Full Name")
age = st.text_input("Age")
birth_date = st.text_input("Birth Date")
birth_place = st.text_input("Birth Place")
lrn = st.text_input("LRN (optional)")
grade_level = st.text_input("Enrolling for Grade Level")
address = st.text_input("Home Address")
contact = st.text_input("Contact Details")
previous_school = st.text_input("Previous School (optional)")

st.subheader("B. Family Data")
parent_name = st.text_input("Parent's Full Name")
parent_age = st.text_input("Parent's Age")
parent_nationality = st.text_input("Nationality")
parent_religion = st.text_input("Religion")
parent_contact = st.text_input("Contact Number")
parent_education = st.text_input("Highest Educational Attainment")
parent_employment = st.text_input("Type of Employment")

st.subheader("C. Guardian Information")
guardian_name = st.text_input("Guardian Full Name")
guardian_relation = st.text_input("Relationship to the Student")
guardian_address = st.text_input("Guardian Address")
guardian_contact = st.text_input("Guardian Contact Number")

class StyledPDF(FPDF):
    def header(self):
        if os.path.exists("/mnt/data/b0733dab-4e67-41cb-85fd-6d84503f58f7.png"):
            self.image("/mnt/data/b0733dab-4e67-41cb-85fd-6d84503f58f7.png", x=10, y=8, w=25)

        self.set_font("Arial", "B", 14)
        self.cell(0, 10, safe_text("SCHOOL OF EVERLASTING PEARL, INC."), ln=True, align="C")
        self.set_font("Arial", "", 10)
        self.cell(0, 5, safe_text("#066 Sitio Suuga Village - Phase III, Marcos Highway, Mambugan, Antipolo City 1870"), ln=True, align="C")
        self.cell(0, 5, safe_text("Email: sepi402954@gmail.com | sepiregistrar@gmail.com"), ln=True, align="C")
        self.cell(0, 5, safe_text("DepEd School ID No.: 402954 | ESC School ID No.: 403694"), ln=True, align="C")
        self.cell(0, 5, safe_text("Government Recognition Nos.: K-042 s.2009 | E-041 s.2012 | 026 s.2011"), ln=True, align="C")
        self.ln(5)
        self.set_font("Arial", "B", 12)
        self.cell(0, 10, safe_text("ENROLLMENT FORM"), ln=True, align="C")
        self.ln(5)

    def section_title(self, title):
        self.set_font("Arial", "B", 12)
        self.set_fill_color(220, 220, 220)
        self.cell(0, 10, safe_text(title), ln=True, fill=True)

    def section_body(self, body):
        self.set_font("Arial", size=11)
        self.multi_cell(0, 8, safe_text(body))
        self.ln(2)

def generate_pdf(data):
    filename = f"enrollment_{uuid4().hex}.pdf"
    pdf = StyledPDF()
    pdf.add_page()

    pdf.section_title("A. Personal Data")
    pdf.section_body(f"""
Full Name: {data['full_name']}
Age: {data['age']}
Birth Date: {data['birth_date']}
Birth Place: {data['birth_place']}
LRN: {data.get('lrn') or 'N/A'}
Grade Level: {data['grade_level']}
Address: {data['address']}
Contact: {data['contact']}
Previous School: {data.get('previous_school') or 'N/A'}
""")

    pdf.section_title("B. Family Data")
    pdf.section_body(f"""
Parent Name: {data['parent_name']}
Age: {data['parent_age']}
Nationality: {data['parent_nationality']}
Religion: {data['parent_religion']}
Contact: {data['parent_contact']}
Education: {data['parent_education']}
Employment: {data['parent_employment']}
""")

    pdf.section_title("C. Guardian Information")
    pdf.section_body(f"""
Guardian Name: {data['guardian_name']}
Relation: {data['guardian_relation']}
Address: {data['guardian_address']}
Contact: {data['guardian_contact']}
""")

    pdf.output(filename)
    return filename

if st.button("Generate PDF"):
    data = {
        'full_name': full_name,
        'age': age,
        'birth_date': birth_date,
        'birth_place': birth_place,
        'lrn': lrn,
        'grade_level': grade_level,
        'address': address,
        'contact': contact,
        'previous_school': previous_school,
        'parent_name': parent_name,
        'parent_age': parent_age,
        'parent_nationality': parent_nationality,
        'parent_religion': parent_religion,
        'parent_contact': parent_contact,
        'parent_education': parent_education,
        'parent_employment': parent_employment,
        'guardian_name': guardian_name,
        'guardian_relation': guardian_relation,
        'guardian_address': guardian_address,
        'guardian_contact': guardian_contact
    }
    filename = generate_pdf(data)
    with open(filename, "rb") as f:
        st.download_button(label="📥 Download PDF", data=f, file_name=filename, mime="application/pdf")
