# -*- coding: utf-8 -*-
"""SEPIEnrollment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wcfQiDTvX6LtuKxQkBn1l4UbkBupEY6a
"""
# streamlit_enrollment_form.py
import streamlit as st
from fpdf import FPDF
from uuid import uuid4
from datetime import datetime
import os
import unicodedata

def safe_text(text):
    return unicodedata.normalize("NFKD", text).encode("latin-1", "ignore").decode("latin-1")

st.set_page_config(page_title="School of Everlasting Pearl, Inc Enrollment System")
st.title("📄 School of Everlasting Pearl, Inc Enrollment System")

st.subheader("A. Personal Data")
full_name = st.text_input("Full Name")
age = st.text_input("Age")
birth_date = st.text_input("Birth Date")
birth_place = st.text_input("Birth Place")
lrn = st.text_input("LRN (optional)")
grade_level = st.text_input("Enrolling for Grade Level")
address = st.text_input("Home Address")
contact = st.text_input("Contact Details")
previous_school = st.text_input("Previous School (optional)")

st.subheader("B. Family Data")
mother_name = st.text_input("Mother's Full Name")
mother_age = st.text_input("Mother's Age")
mother_nationality = st.text_input("Mother's Nationality")
mother_religion = st.text_input("Mother's Religion")
mother_contact = st.text_input("Mother's Contact Number")
mother_education = st.text_input("Mother's Highest Educational Attainment")
mother_employment = st.text_input("Mother's Employment")

dad_name = st.text_input("Father's Full Name")
dad_age = st.text_input("Father's Age")
dad_nationality = st.text_input("Father's Nationality")
dad_religion = st.text_input("Father's Religion")
dad_contact = st.text_input("Father's Contact Number")
dad_education = st.text_input("Father's Highest Educational Attainment")
dad_employment = st.text_input("Father's Employment")

marital_status = st.text_input("Parents' Marital Status")

st.subheader("C. Guardian Information")
guardian_name = st.text_input("Guardian Full Name")
guardian_relation = st.text_input("Relationship to the Student")
guardian_address = st.text_input("Guardian Address")
guardian_contact = st.text_input("Guardian Contact Number")

class StyledPDF(FPDF):
    def header(self):
        if os.path.exists("logo.png"):
            self.image("logo.png", x=10, y=8, w=25)
        self.set_font("Arial", "B", 12)
        self.cell(0, 8, safe_text("SCHOOL OF EVERLASTING PEARL, INC."), ln=True, align="C")
        self.set_font("Arial", "", 8)
        self.cell(0, 4, safe_text("#066 Sitio Suuga Village - Phase III, Marcos Highway, Mambugan, Antipolo City 1870"), ln=True, align="C")
        self.cell(0, 4, safe_text("Email: sepi402954@gmail.com | sepiregistrar@gmail.com"), ln=True, align="C")
        self.cell(0, 4, safe_text("DepEd School ID No.: 402954 | ESC School ID No.: 403694"), ln=True, align="C")
        self.cell(0, 4, safe_text("Government Recognition Nos.: K-042 s.2009 | E-041 s.2012 | 026 s.2011"), ln=True, align="C")
        self.ln(2)
        self.set_font("Arial", "B", 11)
        self.cell(0, 8, safe_text("ENROLLMENT FORM"), ln=True, align="C")
        self.ln(2)

    def section_title(self, title):
        self.set_font("Arial", "B", 10)
        self.set_fill_color(220, 220, 220)
        self.cell(0, 6, safe_text(title), ln=True, fill=True)

    def section_body(self, body):
        self.set_font("Arial", size=12)
        self.multi_cell(0, 6, safe_text(body))
        self.ln(1)

def generate_pdf(data):
    filename = f"enrollment_{uuid4().hex}.pdf"
    pdf = StyledPDF()
    pdf.add_page()

    pdf.section_title("A. Personal Data")
    pdf.section_body(f"""
Full Name: {data['full_name']}  |  Age: {data['age']}  |  Birth Date: {data['birth_date']}  |  Birth Place: {data['birth_place']}
LRN: {data.get('lrn') or 'N/A'}  |  Grade Level: {data['grade_level']}
Home Address: {data['address']}  |  Contact: {data['contact']}
Previous School: {data.get('previous_school') or 'N/A'}
""")

    pdf.section_title("B. Family Data")
    pdf.section_body(f"""
Mother's Name: {data['mother_name']} | Age: {data['mother_age']} | Nationality: {data['mother_nationality']} | Religion: {data['mother_religion']}
Contact: {data['mother_contact']} | Education: {data['mother_education']} | Employment: {data['mother_employment']}

Father's Name: {data['dad_name']} | Age: {data['dad_age']} | Nationality: {data['dad_nationality']} | Religion: {data['dad_religion']}
Contact: {data['dad_contact']} | Education: {data['dad_education']} | Employment: {data['dad_employment']}

Marital Status: {data['marital_status']}
""")

    pdf.section_title("C. Guardian Information")
    pdf.section_body(f"""
Guardian Name: {data['guardian_name']}  |  Relationship: {data['guardian_relation']}
Address: {data['guardian_address']}  |  Contact: {data['guardian_contact']}
""")

    pdf.section_title("Acknowledgement")
    pdf.multi_cell(0, 6, safe_text("""
I hereby certify that the above information is true and correct to the best of my knowledge. I also commit to comply with all the rules,
regulations, and guidelines set forth by the School of Everlasting Pearl, Inc.
"""))
    pdf.ln(10)
    pdf.cell(0, 6, "Signature: _____________________________", ln=True, align="L")
    pdf.cell(0, 6, "Printed Name of Parent/Guardian/Authorized Representative", ln=True, align="L")
    pdf.ln(5)
    pdf.set_font("Arial", size=10)
    pdf.cell(0, 6, f"Date/Time Submitted: {datetime.now().strftime('%Y-%m-%d %I:%M %p')}", ln=True)

    pdf.output(filename)
    return filename

if st.button("Generate PDF"):
    data = {
        'full_name': full_name,
        'age': age,
        'birth_date': birth_date,
        'birth_place': birth_place,
        'lrn': lrn,
        'grade_level': grade_level,
        'address': address,
        'contact': contact,
        'previous_school': previous_school,
        'mother_name': mother_name,
        'mother_age': mother_age,
        'mother_nationality': mother_nationality,
        'mother_religion': mother_religion,
        'mother_contact': mother_contact,
        'mother_education': mother_education,
        'mother_employment': mother_employment,
        'dad_name': dad_name,
        'dad_age': dad_age,
        'dad_nationality': dad_nationality,
        'dad_religion': dad_religion,
        'dad_contact': dad_contact,
        'dad_education': dad_education,
        'dad_employment': dad_employment,
        'marital_status': marital_status,
        'guardian_name': guardian_name,
        'guardian_relation': guardian_relation,
        'guardian_address': guardian_address,
        'guardian_contact': guardian_contact
    }
    filename = generate_pdf(data)
    with open(filename, "rb") as f:
        st.download_button(label="📥 Download PDF", data=f, file_name=filename, mime="application/pdf")
