# -*- coding: utf-8 -*-
"""SEPIEnrollment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wcfQiDTvX6LtuKxQkBn1l4UbkBupEY6a
"""

# streamlit_enrollment_form.py
import streamlit as st
from fpdf import FPDF
from uuid import uuid4
from datetime import datetime
import os
import unicodedata

# Logo background with 50% transparency and pink highlights
st.markdown(
    """
    <style>
    .stApp::before {
        content: "";
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-image: url('SEPI LOGO.png');
        background-repeat: no-repeat;
        background-position: center;
        background-size: 300px;
        opacity: 0.5;
        z-index: -1;
    }
    .highlight {
        background-color: #ffe6f0;
        color: black;
        padding: 0.25rem 0.5rem;
        border-radius: 0.25rem;
        font-weight: 600;
        display: inline-block;
        margin-bottom: 0.5rem;
    }
    h1.highlight { font-size: 14pt !important; }
    h3.highlight { font-size: 12pt !important; }
    </style>
    """,
    unsafe_allow_html=True
)

def safe_text(text):
    return unicodedata.normalize("NFKD", text).encode("latin-1", "ignore").decode("latin-1")

st.set_page_config(page_title="School of Everlasting Pearl, Inc Enrollment System")
st.markdown('<h1 class="highlight">📄 School of Everlasting Pearl, Inc Enrollment System</h1>', unsafe_allow_html=True)

st.markdown('<h3 class="highlight">A. Personal Data</h3>', unsafe_allow_html=True)
full_name = st.text_input("Full Name")
age = st.text_input("Age")
birth_date = st.text_input("Birth Date")
birth_place = st.text_input("Birth Place")
lrn = st.text_input("LRN (optional)")
grade_level = st.text_input("Enrolling for Grade Level")
address = st.text_input("Home Address")
contact = st.text_input("Contact Details")
previous_school = st.text_input("Previous School (optional)")

st.markdown('<h3 class="highlight">B. Family Data</h3>', unsafe_allow_html=True)
mother_name = st.text_input("Mother's Full Name")
mother_age = st.text_input("Mother's Age")
mother_nationality = st.text_input("Mother's Nationality")
mother_religion = st.text_input("Mother's Religion")
mother_contact = st.text_input("Mother's Contact Number")
mother_education = st.selectbox("Mother's Highest Educational Attainment", ["Elementary", "High School", "College Graduate", "Master's", "Doctorate", "Other"])
mother_employment = st.text_input("Mother's Employment")

dad_name = st.text_input("Father's Full Name")
dad_age = st.text_input("Father's Age")
dad_nationality = st.text_input("Father's Nationality")
dad_religion = st.text_input("Father's Religion")
dad_contact = st.text_input("Father's Contact Number")
dad_education = st.selectbox("Father's Highest Educational Attainment", ["Elementary", "High School", "College Graduate", "Master's", "Doctorate", "Other"])
dad_employment = st.text_input("Father's Employment")

marital_status = st.selectbox("Parents' Marital Status", ["Married", "Separated", "Widowed", "Single Parent", "Other"])

st.markdown('<h3 class="highlight">C. Guardian Information</h3>', unsafe_allow_html=True)
guardian_name = st.text_input("Guardian Full Name")
guardian_relation = st.text_input("Relationship to the Student")
guardian_address = st.text_input("Guardian Address")
guardian_contact = st.text_input("Guardian Contact Number")
