# -*- coding: utf-8 -*-
"""SEPIEnrollment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wcfQiDTvX6LtuKxQkBn1l4UbkBupEY6a
"""

# streamlit_enrollment_form.py
import streamlit as st
from fpdf import FPDF
from uuid import uuid4
from datetime import datetime
import os
import unicodedata
import random
import string

try:
    import qrcode
    QR_AVAILABLE = True
except ImportError:
    QR_AVAILABLE = False

# Styling for background and text color
st.markdown(
    """
    <style>
    .stApp::before {
        content: "";
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-image: url('SEPI LOGO.png');
        background-repeat: no-repeat;
        background-position: center;
        background-size: 300px;
        opacity: 0.5;
        z-index: -1;
    }
    h1, h3, label, .css-10trblm, .css-1kyxreq, .stTextInput label {
        color: #e91e63 !important;
    }
    </style>
    """,
    unsafe_allow_html=True
)

def safe_text(text):
    return unicodedata.normalize("NFKD", text).encode("latin-1", "ignore").decode("latin-1")

def generate_reference():
    return ''.join(random.choices(string.ascii_uppercase + string.digits, k=10))

class StyledPDF(FPDF):
    def header(self):
        if os.path.exists("SEPI LOGO.png"):
            self.image("SEPI LOGO.png", x=10, y=8, w=25)
        self.set_font("Arial", "B", 12)
        self.cell(0, 8, safe_text("SCHOOL OF EVERLASTING PEARL, INC."), ln=True, align="C")
        self.set_font("Arial", "", 8)
        self.cell(0, 4, safe_text("#066 Sitio Suuga Village - Phase III, Marcos Highway, Mambugan, Antipolo City 1870"), ln=True, align="C")
        self.cell(0, 4, safe_text("Email: sepi402954@gmail.com | sepiregistrar@gmail.com"), ln=True, align="C")
        self.cell(0, 4, safe_text("DepEd School ID No.: 402954 | ESC School ID No.: 403694"), ln=True, align="C")
        self.cell(0, 4, safe_text("Government Recognition Nos.: K-042 s.2009 | E-041 s.2012 | 026 s.2011"), ln=True, align="C")
        self.ln(2)
        self.set_font("Arial", "B", 11)
        self.cell(0, 8, safe_text("ENROLLMENT FORM"), ln=True, align="C")
        self.ln(2)

    def section_title(self, title):
        self.set_font("Arial", "B", 12)
        self.set_fill_color(240, 240, 240)
        self.cell(0, 8, safe_text(title), ln=True, fill=True)
        self.dotted_line(10, self.get_y(), 200, self.get_y())
        self.ln(2)

    def section_body(self, body):
        self.set_font("Arial", size=12)
        self.multi_cell(0, 6, safe_text(body))
        self.ln(1)

def generate_pdf(data):
    ref_number = generate_reference()
    surname = data['full_name'].split()[-1].upper() if data['full_name'] else "UNKNOWN"
    filename = f"SEPI_{surname}_{ref_number}.pdf"

    pdf = StyledPDF(orientation='P', unit='mm', format=(203, 330))  # 8x13 inches
    pdf.add_page()

    pdf.set_font("Arial", "I", 8)
    pdf.cell(0, 5, f"Reference No.: {ref_number}", ln=True, align="R")

    pdf.section_title("A. Personal Data")
    pdf.section_body(f"""
Full Name: {data['full_name']}  |  Age: {data['age']}  |  Birth Date: {data['birth_date']}  |  Birth Place: {data['birth_place']}
LRN: {data['lrn'] or 'N/A'}  |  Grade Level: {data['grade_level']}
Address: {data['address']}  |  Contact: {data['contact']}
Previous School: {data['previous_school'] or 'N/A'}
""")

    pdf.section_title("B. Family Data")
    pdf.section_body(f"""
Mother: {data['mother_name']} | Age: {data['mother_age']} | Nationality: {data['mother_nationality']} | Religion: {data['mother_religion']}
Contact: {data['mother_contact']} | Education: {data['mother_education']} | Employment: {data['mother_employment']}

Father: {data['dad_name']} | Age: {data['dad_age']} | Nationality: {data['dad_nationality']} | Religion: {data['dad_religion']}
Contact: {data['dad_contact']} | Education: {data['dad_education']} | Employment: {data['dad_employment']}

Marital Status: {data['marital_status']}
""")

    pdf.section_title("C. Guardian Information")
    pdf.section_body(f"""
Name: {data['guardian_name']} | Relationship: {data['guardian_relation']}
Address: {data['guardian_address']} | Contact: {data['guardian_contact']}
""")

    pdf.section_title("Acknowledgement")
    pdf.section_body(f"""
I hereby certify that the information above is true and correct to the best of my knowledge.
I commit to comply with all school rules and institutional guidelines set forth by SEPI.

Signature over Printed Name of Parent/Guardian/Authorized Representative:

______________________________

Date/Time Submitted: {datetime.now().strftime('%Y-%m-%d %I:%M %p')}
""")

    pdf.section_title("Enrollment Requirements Checklist")
    pdf.set_font("Arial", size=12)
    pdf.cell(5, 6, "☐", border=0)
    pdf.cell(0, 6, safe_text("PSA Birth Certificate"), ln=True)
    pdf.cell(5, 6, "☐", border=0)
    pdf.cell(0, 6, safe_text("Authorization Letter (if applicable) with Valid ID"), ln=True)
    pdf.cell(5, 6, "☐", border=0)
    pdf.cell(0, 6, safe_text("Transfer Credentials (if applicable)"), ln=True)
    pdf.ln(4)

    if QR_AVAILABLE and data['lrn']:
        qr = qrcode.make(data['lrn'])
        qr_path = f"qr_{uuid4().hex}.png"
        qr.save(qr_path)
        pdf.image(qr_path, x=170, y=pdf.get_y(), w=25)
        os.remove(qr_path)

    pdf.output(filename)
    return filename

# Streamlit input form UI
st.title("📄 School of Everlasting Pearl, Inc Enrollment System")

education_levels = ["Elementary", "High School", "College Graduate", "Master's", "Doctorate", "Other"]
employment_types = ["Unemployed", "Self-employed", "Private Sector", "Public Sector", "Overseas", "Other"]
marital_options = ["Married", "Separated", "Widowed", "Single Parent", "Other"]

with st.form("enrollment_form"):
    st.header("A. Personal Data")
    full_name = st.text_input("Full Name")
    age = st.text_input("Age")
    birth_date = st.text_input("Birth Date")
    birth_place = st.text_input("Birth Place")
    lrn = st.text_input("LRN (optional)")
    grade_level = st.text_input("Enrolling for Grade Level")
    address = st.text_input("Home Address")
    contact = st.text_input("Contact Details")
    previous_school = st.text_input("Previous School (optional)")

    st.header("B. Family Data")
    mother_name = st.text_input("Mother's Full Name")
    mother_age = st.text_input("Mother's Age")
    mother_nationality = st.text_input("Mother's Nationality")
    mother_religion = st.text_input("Mother's Religion")
    mother_contact = st.text_input("Mother's Contact Number")
    mother_education = st.selectbox("Mother's Highest Educational Attainment", education_levels)
    mother_employment = st.selectbox("Mother's Employment", employment_types)

    dad_name = st.text_input("Father's Full Name")
    dad_age = st.text_input("Father's Age")
    dad_nationality = st.text_input("Father's Nationality")
    dad_religion = st.text_input("Father's Religion")
    dad_contact = st.text_input("Father's Contact Number")
    dad_education = st.selectbox("Father's Highest Educational Attainment", education_levels)
    dad_employment = st.selectbox("Father's Employment", employment_types)

    marital_status = st.selectbox("Parents' Marital Status", marital_options)

    st.header("C. Guardian Information")
    guardian_name = st.text_input("Guardian Full Name")
    guardian_relation = st.text_input("Relationship to the Student")
    guardian_address = st.text_input("Guardian Address")
    guardian_contact = st.text_input("Guardian Contact Number")

    submitted = st.form_submit_button("Generate PDF")

if submitted:
    required_fields = [full_name, age, birth_date, birth_place, grade_level, address, contact,
                       mother_name, mother_age, mother_nationality, mother_religion, mother_contact,
                       dad_name, dad_age, dad_nationality, dad_religion, dad_contact,
                       marital_status, guardian_name, guardian_relation, guardian_address, guardian_contact]

    if any(field.strip() == "" for field in required_fields):
        st.warning("⚠️ Please fill in all required fields.")
    else:
        data = {
            'full_name': full_name, 'age': age, 'birth_date': birth_date, 'birth_place': birth_place,
            'lrn': lrn, 'grade_level': grade_level, 'address': address, 'contact': contact, 'previous_school': previous_school,
            'mother_name': mother_name, 'mother_age': mother_age, 'mother_nationality': mother_nationality, 'mother_religion': mother_religion,
            'mother_contact': mother_contact, 'mother_education': mother_education, 'mother_employment': mother_employment,
            'dad_name': dad_name, 'dad_age': dad_age, 'dad_nationality': dad_nationality, 'dad_religion': dad_religion,
            'dad_contact': dad_contact, 'dad_education': dad_education, 'dad_employment': dad_employment,
            'marital_status': marital_status, 'guardian_name': guardian_name, 'guardian_relation': guardian_relation,
            'guardian_address': guardian_address, 'guardian_contact': guardian_contact
        }
        filename = generate_pdf(data)
        with open(filename, "rb") as f:
            st.download_button(label="📥 Download PDF", data=f, file_name=filename, mime="application/pdf")
        st.success("✅ PDF generated successfully.")